language: java
before_install:
    - sudo apt-get update
    - sudo apt-get install ruby
install:
    - gem install sass
    - gem install compass
before_script:
    - cd paw-webapp
cache:
    directories:
        - $HOME/.m2
        - node
        - node_modules
        - bower_components
notifications:
  # Telegram notifications
  webhooks:
    urls:
      - https://fathomless-fjord-24024.herokuapp.com/notify
    # Notifies everyone who talked with the bot, so only notify bad stuff
    on_success: never
    on_failure: always
    on_start: never
    on_cancel: never
    on_error: always