language: java
before_install:
    - sudo apt-get update
    - sudo apt-get install ruby
install:
    - gem install sass
    - gem install compass
before_script:
    - cd paw-webapp
cache:
    directories:
        - $HOME/.m2
        - node
        - node_modules
        - bower_components
notifications:
    webhooks:
        urls:
            - https://fathomless-fjord-24024.herokuapp.com/notify
        on_success: never
        on_failure: always
        on_error: always
        on_cancel: always
    email:
        recipients:
            - juanmbellini@gmail.com
            - juanlipuma94@gmail.com
            - ddegrimaudetderocheb@itba.edu.ar
            - julrodriguez@itba.edu.ar
        on_sucess: always
        on_failure: always
        on_error: always
        on_cancel: always
